"""reshape busy week seed: purge seed calls so day_offset=0 + denser -1 reseed

Revision ID: 0017
Revises: 0016
Create Date: 2026-05-19

`_busy_week_specs` has been rebalanced to:
  - introduce day_offset=0 (two early-morning slots) so the demo shows
    "today" activity on a fresh install;
  - densify day_offset=-1 to surface booking/client rows at the top of
    the Calls feed instead of mock/anonymous noise.

Existing seed `Call` rows were materialized with the OLD plan and use
UUID5(phone, day_offset, slot_idx) — a partial overlap with the new plan,
but slot indices and customer assignments have shifted, so the safest path
is a full purge of seed rows. `seed.py` short-circuits when seed templates
are present, so without this purge the new plan would never materialize on
a deployed DB.

Order is FK-safe (no cascade configured on audit_log / customer_memory_chunks):
  1. customer_memory_chunks (FK → calls.id)
  2. audit_log              (FK → calls.id, no cascade)
  3. calls                  (executed_actions / extracted_fields cascade)

`settings.seed_anchor_date` is intentionally preserved so the lifespan
refresh task computes the correct shift on the next boot.

Coherent with feedback_db_disposable.md: seed data is disposable.
"""
from typing import Sequence, Union

from alembic import op


revision: str = "0017"
down_revision: Union[str, None] = "0016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Children of seed Call rows first (no FK cascade on these two).
    op.execute(
        """
        DELETE FROM customer_memory_chunks
        WHERE call_id IN (SELECT id FROM calls WHERE is_seed = TRUE)
        """
    )
    op.execute(
        """
        DELETE FROM audit_log
        WHERE call_id IN (SELECT id FROM calls WHERE is_seed = TRUE)
        """
    )
    # executed_actions + extracted_fields cascade on calls.id deletion.
    op.execute("DELETE FROM calls WHERE is_seed = TRUE")


def downgrade() -> None:
    # No-op: seed rows are regenerated by `seed.py` on the next boot.
    # Downgrading this migration does not restore the pre-purge dataset
    # (which was itself materialized by the seed script).
    pass
